workspace "PlantWater-API-server Architecture" "Project-level architecture generated by Barkly Docs." {
    model {
        project = softwareSystem "PlantWater-API-server" "System analyzed by Barkly Docs." {
            auth_py = container "auth.py" "Top-level project area. 1 source file(s); 7 indexed code element(s)." "Software"
            bot = container "bot" "Top-level project area. 1 source file(s); 19 indexed code element(s)." "Software"
            carriers_py = container "carriers.py" "Top-level project area. 1 source file(s); 3 indexed code element(s)." "Software"
            config = container "config" "Top-level project area. 1 source file(s); 2 indexed code element(s)." "Software"
            db_py = container "db.py" "Top-level project area. 1 source file(s); 5 indexed code element(s)." "Software"
            deps_py = container "deps.py" "Top-level project area. 1 source file(s); 2 indexed code element(s)." "Software"
            esp32_firmware = container "esp32-firmware" "Top-level project area. 8 source file(s); 65 indexed code element(s)." "Software"
            main_py = container "main.py" "Top-level project area. 1 source file(s); 1 indexed code element(s)." "Software"
            manifest_json = container "manifest.json" "Top-level project area. 1 source file(s); 2 indexed code element(s)." "Software"
            models_py = container "models.py" "Top-level project area. 1 source file(s); 9 indexed code element(s)." "Software"
            Project_root = container "Project root" "Top-level project area. 2 source file(s); 4 indexed code element(s)." "Software"
            routes = container "routes" "Top-level project area. 9 source file(s); 92 indexed code element(s)." "Software"
            schemas_py = container "schemas.py" "Top-level project area. 1 source file(s); 12 indexed code element(s)." "Software"
            services = container "services" "Top-level project area. 2 source file(s); 13 indexed code element(s)." "Software"
            sim = container "sim" "Top-level project area. 11 source file(s); 53 indexed code element(s)." "Software"
            static = container "static" "Top-level project area. 1 source file(s); 2 indexed code element(s)." "Software"
            watchdog_py = container "watchdog.py" "Top-level project area. 1 source file(s); 3 indexed code element(s)." "Software"
        }
        project.auth_py -> project.db_py "connects to (10) — calls, imports"
        project.auth_py -> project.deps_py "connects to (1) — contains"
        project.auth_py -> project.models_py "connects to (2) — imports"
        project.bot -> project.db_py "connects to (8) — calls"
        project.bot -> project.routes "connects to (3) — calls, contains"
        project.db_py -> project.routes "connects to (1) — calls"
        project.deps_py -> project.db_py "connects to (1) — imports"
        project.deps_py -> project.models_py "connects to (1) — imports"
        project.esp32_firmware -> project.db_py "connects to (3) — imports"
        project.esp32_firmware -> project.main_py "connects to (1) — contains"
        project.esp32_firmware -> project.models_py "connects to (5) — imports"
        project.esp32_firmware -> project.routes "connects to (8) — imports"
        project.esp32_firmware -> project.sim "connects to (21) — calls, contains, imports"
        project.models_py -> project.db_py "connects to (1) — imports"
        project.routes -> project.auth_py "connects to (11) — calls, imports"
        project.routes -> project.db_py "connects to (201) — calls, imports"
        project.routes -> project.esp32_firmware "connects to (13) — calls"
        project.routes -> project.models_py "connects to (21) — imports"
        project.routes -> project.schemas_py "connects to (10) — imports"
        project.routes -> project.services "connects to (18) — calls, imports"
        project.routes -> project.sim "connects to (7) — calls"
        project.schemas_py -> project.carriers_py "connects to (1) — imports"
        project.services -> project.db_py "connects to (10) — calls"
        project.services -> project.esp32_firmware "connects to (16) — calls"
        project.services -> project.models_py "connects to (3) — imports"
    }
    views {
        container project "project-overview" "Project-level component dependencies" {
            include *
            autolayout lr
        }
        styles {
            element "Software System" { background #171117 color #FFD5E6 stroke #FF6B9D }
            element "Container" { shape RoundedBox background #2A1B27 color #FFD5E6 stroke #FF6B9D }
            relationship { color #7DFFB2 routing Orthogonal }
        }
    }
}
